const BRIGHTDATA_API='https://api.brightdata.com/datasets/v3';
const API_KEY=process.env.BRIGHTDATA_API_KEY!;
export const DATASETS={google_search:'gd_l1vikfnt1wgvvqz95w',amazon_search:'gd_l7q7dkf244hwjntr0',google_shopping:'gd_lwhidru92ywb3n2hn'};
export interface ScrapeResult{url?:string;title?:string;description?:string;price?:string;seller?:string;platform?:string;[key:string]:unknown;}
import { saveMonitoringResult } from './products';

export interface MonitoringResult{snapshotId?:string;results:ScrapeResult[];violations:ScrapeResult[];platform:string;query:string;}
export async function triggerSearch(query:string,dataset: keyof typeof DATASETS='amazon_search'):Promise<string>{const datasetId=DATASETS[dataset];let searchUrl='';switch(dataset){case 'amazon_search':searchUrl=`https://www.amazon.com/s?k=${encodeURIComponent(query)}`;break;case 'google_shopping':searchUrl=`https://www.google.com/search?q=${encodeURIComponent(query)}&tbm=shop`;break;case 'google_search':default:searchUrl=`https://www.google.com/search?q=${encodeURIComponent(query)}`;}const res=await fetch(`${BRIGHTDATA_API}/trigger?dataset_id=${datasetId}&format=json&uncompressed_webhook=true`,{method:'POST',headers:{Authorization:`Bearer ${API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify([{url:searchUrl}])});if(!res.ok){const err=await res.text();throw new Error(`Brightdata trigger failed: ${err}`);}const data=await res.json();return data.snapshot_id as string;}
export async function getSnapshot(snapshotId:string):Promise<ScrapeResult[]> {const res=await fetch(`${BRIGHTDATA_API}/snapshot/${snapshotId}?format=json`,{headers:{Authorization:`Bearer ${API_KEY}`}});if(res.status===202)return[];if(!res.ok)throw new Error(`Brightdata snapshot fetch failed: ${res.status}`);return res.json();}
export async function scrapeSync(query:string,dataset: keyof typeof DATASETS='amazon_search'):Promise<ScrapeResult[]> {const datasetId=DATASETS[dataset];let searchUrl='';switch(dataset){case 'amazon_search':searchUrl=`https://www.amazon.com/s?k=${encodeURIComponent(query)}`;break;case 'google_shopping':searchUrl=`https://www.google.com/search?q=${encodeURIComponent(query)}&tbm=shop`;break;case 'google_search':default:searchUrl=`https://www.google.com/search?q=${encodeURIComponent(query)}`;}const res=await fetch(`${BRIGHTDATA_API}/scrape?dataset_id=${datasetId}&format=json`,{method:'POST',headers:{Authorization:`Bearer ${API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify([{url:searchUrl}])});if(!res.ok){const err=await res.text();throw new Error(`Brightdata scrape failed: ${err}`);}return res.json();}
export function detectViolations(results:ScrapeResult[],trademark:string):ScrapeResult[]{const lower=trademark.toLowerCase();return results.filter(r=>{const text=`${r.title??''} ${r.description??''} ${r.seller??''}`.toLowerCase();return text.includes(lower);});}
export async function runMonitoring(trademark:string,keywords:string[]=[],mode:'sync'|'async'='async',productId?:string,userId?:string):Promise<MonitoringResult[]> {const results: MonitoringResult[] = []; const dataset: keyof typeof DATASETS = 'amazon_search'; const queries = keywords.length ? keywords : [trademark]; for (const q of queries) {const snapshotId = await triggerSearch(q,dataset); const scraped = await getSnapshot(snapshotId); const violations = detectViolations(scraped,trademark); results.push({results: scraped, violations, platform: 'amazon', query: q}); if (productId && userId) {await saveMonitoringResult({product_id: productId, user_id: userId, platform: 'amazon', search_query: q, results: scraped, violations, violation_count: violations.length, snapshot_id: snapshotId});}} return results; }
